### ISSUE TITLE
libkmc.so not found

### ISSUE THREAD

**Issue by ghost** [AlgoLab/malva#14]
Hello, I have installed MALVA following the conda approach but it returns

```error while loading shared libraries: libkmc.so: cannot open shared object file: No such file or directory```

Is there an issue with the bioconda recipe? thanks

**Comment by yp** [comment]
Hi, thanks for reporting back the problem. We are working for fixing the recipe. I will let you know as soon as the new version appears in the bioconda channel.

**Comment by yp** [comment]
Hi @Axze-rgb, the version fixing the issue is now available in bioconda. Thanks again.
