### ISSUE TITLE
MALVA (malva-geno?) gets killed

### ISSUE THREAD

**Issue by DiDeoxy** [AlgoLab/malva#2]
I installed Malva using conda into a docker contianer and am running it with Nextflow.

```
RUN conda update conda \
    && conda install -c bioconda malva=1.1.1
```

The command to run MALVA is:

```
#!/bin/bash -ue
MALVA \
  GRCh38_full_analysis_set_plus_decoy_hla.fa \
  ALL.chr1.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz \
  GRC194242437_trimmed.fq.gz \
  > GRC194242437.vcf
```
Thre known variants are the 1000 Genomes 2019 high-depth GRCH38 variants.

I am using the 1000 Genomes version of GRCh38.

The fastq file is from a concatentation of paired-end reads (i.e. all read1 hen all read2; not interlaced). They contain only 1x worth of reads.

The MALVA script outputs:

```
[MALVA] Running KMC
[MALVA] Running malva-geno
[malva-geno/Reference parsing] Time elapsed 0s
[malva-geno/Reference processed] Time elapsed 10s
[malva-geno/VCF parsing (Bloom Filter construction)] Time elapsed 10s
/home/maxh/conda/bin/MALVA: line 93: 13284 Killed                  ${EXECUTABLE} -k ${k} -r ${refk} -e ${erate} -f ${freq} -s ${samples} -c ${maxcov} -b ${bfsize} ${reference} ${vcf_file} ${kmc_out_prefix}
[MALVA] Cleaning up
```

Thus KMC and malva-geno run but the run times of malva-geno are suspiciously short. I don't quite understand why bash prints out the line from MALVA that it does as this is not line 93, it is line 97 and it is what runs malva-geno. Infact it should never get to line 93 as this is only reached is kmc_pre and kmc_suf are not present.

What could be the cause? Resources? I limit MALVA to 8GB currently, is that too low?

**Comment by ldenti** [comment]
Hi,
thank you for trying malva on your data.

> What could be the cause? Resources? I limit MALVA to 8GB currently, is that too low?

I think that you already caught the problem: by default, MALVA builds two bloom filters of 4GB (see argument -b). Therefore, I suggest you to increase the amount of RAM available. If you can't, you can decrease the Bloom filter size: how many variants are contained in the input VCF?

**Comment by mpre** [comment]
I'm closing this issue since we didn't get any answer for more than a year.
