### ISSUE TITLE
vcfs can have "chr" in the chromosome name

### ISSUE THREAD

**Issue by mchaisso** [AlgoLab/malva#3]
malva-geno crashes when the vcf has "chr" in a name. Commenting out the section of main.cpp that strips "chr" from the id in the reference map lets malva run fine. I'd recommend placing the burden on the users to match vcf and reference naming conventions.

**Comment by mpre** [comment]
Hi Mark, thank you for the suggestion.  We changed the default behavior and made the old one optional (-p flag).

Reference #4
