### ISSUE TITLE
Installation failure, can't find htslib

### ISSUE THREAD

**Issue by OliverPStuart** [AlgoLab/malva#7]
I'm trying to get MALVA installed on a Linux server (`Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-112-generic x86_64)`) following the instructions on the README in the root directory and get the following error:

`./malva-geno: error while loading shared libraries: libhts.so.3: cannot open shared object file: No such file or directory`

No changes were made to the build instructions, and there were no reported errors during compilation of sdsl-lite, kmc, and htslib, or MALVA itself.

**Comment by mpre** [comment]
Hi, seems that the the shared libraries are not loaded.  Prepending `LD_PRELOAD=<path-to-libhts.so>` to `malva-geno` should do the trick.

**Comment by OliverPStuart** [comment]
Yep, that did the trick. Thanks!

**Comment by ldenti** [comment]
I'm closing this since it has been solved.

btw for future reference it is also possible to export the `LD_PRELOAD` variable to make it available to all child processes run in the same shell (reference: https://github.com/genome/pindel/issues/101):
```
export LD_LIBRARY_PATH=<path-to-libhts.so>
malva-geno
```
